version: "3.7"

volumes:
    cells_working_dir: {}
    cells_data: {}
    mysql_data: {}

services:
  # DB backend
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=rpwd
      - MYSQL_DATABASE=cells
      - MYSQL_USER=pydio
      - MYSQL_PASSWORD=pwd
    cap_add: 
      - SYS_NICE 
    command: 
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default_authentication_plugin=mysql_native_password


# Pydio Cells app
  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    # Not compulsory but it eases some of the maintenance operations. 
    hostname: cells
    expose:
      - 443
    volumes:
      - cells_working_dir:/var/cells
      - cells_data:/data
      - ./metrics:/var/cells/services/pydio.gateway.metrics
    environment:
      - CELLS_WORKING_DIR=/var/cells
      - CELLS_DATA=/data
      - CELLS_BIND=test.luchier.fr:443
      - CELLS_EXTERNAL=https://test.luchier.fr
      - CELLS_ENABLE_METRICS=true
    depends_on:
      - mysql
